GET http://localhost:3000/api/v1/users/me
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImlkIjoxLCJlbWFpbCI6InlrYWhyYW1hbkBob3RtYWlsLmNvbSJ9LCJleHAiOjE3NTE0NDczMTksImlhdCI6MTc1MTQ0NzEzOSwiaXNzIjoicmFpbHNfand0X2FwaSIsImF1ZCI6InJhaWxzX2p3dF9jbGllbnQiLCJzdWIiOiJVc2VyIiwianRpIjoiODU3MGM1ZjQtMjM1OC00Yzk2LTlmOWUtOTIxYzUzMGZjOWNkIiwibmJmIjoxNzUxNDQ3MTQwfQ.F96eEaD9U8h7D0G9bSV2yqRel7vHv7tCkOE01dWoxc4